
CREATE TABLE IF NOT EXISTS `Players`(
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `strength` INTEGER NOT NULL DEFAULT 50,
  `wealth` INTEGER NOT NULL DEFAULT 50,
  `monster_tally` INTEGER NOT NULL DEFAULT 0,
  `current_room` INTEGER NULL);
